MODEL:
  TYPE: "UDA_Segmentor"
  BACKBONE:
    TYPE: "R-DL-50-C1-C5"
    PRETRAINED: True
    WITH_IBN: False  
  DECODER:
    TYPE: "DeepLabV2Dedoder"
  PREDICTOR:
    TYPE: "BasePredictor"
    NUM_CLASSES: 19
    LOSS: "CrossEntropy"
  DISCRIMINATOR:
    # TYPE: ["R18-Predictor",]
    TYPE: ["Base-Predictor-SN",]
    WEIGHT: [0.001,]
    LR: [0.0001]
TRAIN:
  EPOCHES: 20
  OPTIMIZER: "Adam"
  LR: 0.00025
  BATCHSIZE: 8
  ITER_REPORT: 50
  # SCHEDULER: ""
  SCHEDULER: "CosineAnnealingLR_with_Restart"
  COSINEANNEALINGLR:
    T_MAX: 5
    T_MULT: 1.0
  SAVE_ALL: False
DATASET:
  TYPE: "small-GTAVDataset"
  ANNS: "../data/gtav_train.json"
  IMAGEDIR: "../data/GTA5"
  USE_AUG: True
  NUM_SAMPLES: 4000
  VAL:
    TYPE: "small-CityscapesDataset"
    ANNS: "../data/cityscapes_val.json"
    IMAGEDIR: "../data/cityscapes"
    RESIZE_SIZE: [512, 256]
  TARGET:
    TYPE: "small-CityscapesDataset"
    ANNS: "../data/cityscapes_train.json"
    IMAGEDIR: "../data/cityscapes"
WORK_DIR: "test_log/small/cos-Base-Predictor-SN"