MODEL:
  BACKBONE:
    TYPE: "R-DL-50-C1-C5"
    PRETRAINED: True
    WITH_IBN: False  
  DECODER:
    TYPE: "DeepLabV2Dedoder"
  PREDICTOR:
    TYPE: "UpsamplePredictor"
    NUM_CLASSES: 19
    LOSS: "CrossEntropy"
TRAIN:
  EPOCHES: 20
  OPTIMIZER: "Adam"
  LR: 0.0002
  BATCHSIZE: 16
  ITER_REPORT: 25
  # SCHEDULER: "CosineAnnealingLR_with_Restart"
  # COSINEANNEALINGLR:
  #   T_MAX: 5
  #   T_MULT: 1.0
  SAVE_ALL: False
DATASET:
  TYPE: "small-GTAVDataset"
  ANNS: "../data/gtav_train.json"
  IMAGEDIR: "../data/GTA5"
  USE_AUG: True
  NUM_SAMPLES: 4000
  VAL:
    TYPE: "small-CityscapesDataset"
    ANNS: "../data/cityscapes_val.json"
    IMAGEDIR: "../data/cityscapes"
    RESIZE_SIZE: [640, 320]
WORK_DIR: "small_log/self_adam_lr2e-4_bs16"