MODEL:
  TYPE: "UDA_Segmentor"
  BACKBONE:
    TYPE: "R-DL-101-C1-C5"
    PRETRAINED: True
    WITH_IBN: False  
  DECODER:
    TYPE: "DeepLabV2Dedoder"
  PREDICTOR:
    TYPE: "UpsamplePredictor"
    NUM_CLASSES: 19
    LOSS: "CrossEntropy"
  DISCRIMINATOR:
    TYPE: ["Origin-Predictor",]
    WEIGHT: [0.001,]
    LR: [0.0002]
    LOSS: "MSELoss"
TRAIN:
  EPOCHES: 40
  OPTIMIZER: "Adam"
  LR: 0.0002
  BATCHSIZE: 4
  ITER_REPORT: 100
  # SCHEDULER: "CosineAnnealingLR_with_Restart"
  # COSINEANNEALINGLR:
  #   T_MAX: 5
  #   T_MULT: 1.0
  SAVE_ALL: False
DATASET:
  TYPE: "GTAVDataset"
  ANNS: "../data/gtav_train.json"
  IMAGEDIR: "../data/GTA5"
  USE_AUG: True
  NUM_SAMPLES: 4000
  VAL:
    TYPE: "CityscapesDataset"
    ANNS: "../data/cityscapes_val.json"
    IMAGEDIR: "../data/cityscapes"
    RESIZE_SIZE: [1280, 640]
  TARGET:
    TYPE: "CityscapesDataset"
    ANNS: "../data/cityscapes_train.json"
    IMAGEDIR: "../data/cityscapes"
# WORK_DIR: "../log/r50-unet-d5"
# WORK_DIR: "test_log/r50-unet-d5-mini"
# WORK_DIR: "test_log/base-Decoder"
WORK_DIR: "../log/mse_fcD"