MODEL:
  BACKBONE:
    TYPE: "R-DL-101-C1-C5"
    PRETRAINED: True
    WITH_IBN: False  
  DECODER:
    TYPE: "DeepLabV2Dedoder"
  PREDICTOR:
    TYPE: "BasePredictor"
    NUM_CLASSES: 19
    LOSS: "CrossEntropy"
TRAIN:
  EPOCHES: 20
  OPTIMIZER: "Adam"
  LR: 0.0001
  BATCHSIZE: 4
  ITER_REPORT: 100
  # SCHEDULER: "CosineAnnealingLR_with_Restart"
  # COSINEANNEALINGLR:
  #   T_MAX: 5
  #   T_MULT: 1.0
  SAVE_ALL: False
DATASET:
  TYPE: "GTAVDataset"
  ANNS: "../data/gtav_mini_train.json"
  IMAGEDIR: "../data/GTA5"
  USE_AUG: True
  NUM_SAMPLES: 2000
  VAL:
    TYPE: "CityscapesDataset"
    ANNS: "../data/cityscapes_val.json"
    IMAGEDIR: "../data/cityscapes"
    RESIZE_SIZE: [1024, 512]
WORK_DIR: "test_log/test_sampler"