MODEL:
  BACKBONE:
    TYPE: "R-50-C1-C5"
    PRETRAINED: True
    WITH_IBN: False  
  DECODER:
    TYPE: "UnetDecoder-D5"
  PREDICTOR:
    TYPE: "BasePredictor"
    NUM_CLASSES: 2
    LOSS: "diceloss"
TRAIN:
  EPOCHES: 20
  OPTIMIZER: "Ranger"
  LR: 0.001
  BATCHSIZE: 8
  ITER_REPORT: 100
  # SCHEDULER: "CosineAnnealingLR_with_Restart"
  # COSINEANNEALINGLR:
  #   T_MAX: 5
  #   T_MULT: 1.0
  SAVE_ALL: True
DATASET:
  TYPE: "DigestDataset"
  ANNS: "../digest/train_010.json"
  IMAGEDIR: "../digest/tissue-train-pos"
  USE_AUG: True
  RESIZE_SIZE: [512, 512]
  VAL:
    TYPE: "DigestDataset"
    ANNS: "../digest/val_010.json"
    IMAGEDIR: "../digest/tissue-train-pos"
    RESIZE_SIZE: [512, 512]
WORK_DIR: "log/test"