MODEL:
  TYPE: "UDA_Segmentor"
  BACKBONE:
    TYPE: "R-50-C1-C5"
    PRETRAINED: True
    WITH_IBN: True  
  DECODER:
    TYPE: "UnetDecoderV2-D1-D5-UDA"
  PREDICTOR:
    TYPE: "BasePredictor"
    NUM_CLASSES: 2
    LOSS: "diceloss"
  DISCRIMINATOR:
    TYPE: ["Encoder", "Decoder"]
    WEIGHT: [0.01, 0.001]
    LR: [0.0001, 0.0001]
TRAIN:
  EPOCHES: 20
  OPTIMIZER: "Adam"
  LR: 0.0001
  BATCHSIZE: 8
  ITER_REPORT: 100
  # SCHEDULER: "CosineAnnealingLR_with_Restart"
  # COSINEANNEALINGLR:
  #   T_MAX: 10
  #   T_MULT: 1.0
  SAVE_ALL: True
DATASET:
  TYPE: "DigestDataset"
  ANNS: "../digest/train_010_s.json"
  IMAGEDIR: "../digest/tissue-train-pos"
  USE_AUG: True
  RESIZE_SIZE: [512, 512]
  VAL:
    TYPE: "DigestDataset"
    ANNS: "../digest/val_010.json"
    IMAGEDIR: "../digest/tissue-train-pos"
    RESIZE_SIZE: [512, 512]
  TARGET:
    TYPE: "DigestDataset"
    ANNS: "../digest/train_010_t.json"
    IMAGEDIR: "../digest/tissue-train-pos"
WORK_DIR: "log/sda-ed"